#!/bin/bash

SIDE=$1
KB_NAME=${KB_NAME:-KB}
KB_MAIN=${KB_MAIN:-main}
if [[ "$SIDE" != "L" ]] && [[ "$SIDE" != "R" ]]; then
    echo "Usage: hack/init L|R"
    exit 1
fi

DIR="$(dirname ${BASH_SOURCE[0]})"
KB_DRIVE=/Volumes/${KB_NAME}_${SIDE}
MAIN_PY=boards/pwhitesell/${KB_MAIN}.py
RGB_KEYS=kmk/modules/rgbkeys.py
PMW=kmk/modules/pmw3360.py
CAPSWORD=kmk/modules/capsword.py
SPLIT=kmk/modules/split.py
RGB=kmk/extensions/rgb.py
KB=kmk/kmk_keyboard.py

echo SIDE     =     $SIDE
echo KB_NAME  =     $KB_NAME
echo DIR      =     $DIR
echo KB_DRIVE =     $KB_DRIVE
echo MAIN_PY  =     $MAIN_PY
echo RGB_KEYS =     $RGB_KEYS
echo PMW      =     $PMW
echo CAPSWORD =     $CAPSWORD
echo SPLIT    =     $SPLIT
echo RGB      =     $RGB
echo KB       =     $KB

function copy() {
    from=$DIR/../$1
    to=$KB_DRIVE/$2
    echo "copying"
    echo "  $from"
    echo "  ==>"
    echo "  $to"
    echo "..."
    cp -X $from $to
}

copy $MAIN_PY code.py
# copy boards/pwhitesell/keys.py

for m in $PMW; do
    copy $m kmk/modules
done
# for e in $RGB; do
#     copy $e kmk/extensions
# done
# for f in $(ls $DIR/../kmk | grep ".py"); do
#     copy kmk/$f kmk/
# done
# cp -X $KB $KB_DRIVE/kmk