#!/bin/bash
SIDE=${SIDE:-R}
KB=${KB:-adjustable}

# libs
# circup --path /Volumes/KBA_$SIDE install adafruit_bus_device
# circup --path /Volumes/KBA_$SIDE install neopixel
# cp -X ../CircuitPython_PMW3360/pmw3360.py /Volumes/KBA_$SIDE/lib/

# # kmk
# cp -r -X ./kmk /Volumes/KBA_$SIDE/

# # board
# cp -X ./boards/pwhitesell/keys.py /Volumes/KBA_$SIDE/keys.py
cp -X ./boards/pwhitesell/${KB}.py /Volumes/KBA_$SIDE/code.py
